Parameters:

  VPC:
    Description: Default VPC
    Type: String
    Default: defvpc

  SubnetA:
    Description: Default SubnetA
    Type: String
    Default: defsuba

  SubnetB:
    Description: Default SubnetB
    Type: String
    Default: defsubb

  SubnetC:
    Description: Default SubnetC
    Type: String
    Default: defsubc

Resources:
  
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: app
      Cpu: 256
      Memory: 256
      NetworkMode: bridge
      ContainerDefinitions:
        - Name: engage-app
          Image: imageapp
          Cpu: 256
          Memory: 256
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: engage-service
      TaskDefinition: !Ref Task
      Cluster: !ImportValue 'ECSCluster'
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      LoadBalancers:
        - ContainerName: engage-app
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: engage-app-tg
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: instance

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue 'Listener'
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
